import type { EditorTheme, MarkdownHeadingTokens } from "./types";

export function markdownToCssVariables(theme: EditorTheme): Record<string, string> {
  const markdown = theme.markdown;
  return {
    "--markdown-font-body": markdown.font.familyBody,
    "--markdown-font-heading": markdown.font.familyHeading,
    "--markdown-font-code": markdown.font.familyCode,
    "--markdown-body-color": markdown.body.color,
    "--markdown-body-font-size": `${markdown.body.fontSize}px`,
    "--markdown-body-line-height": `${markdown.body.lineHeight}px`,
    "--markdown-body-font-weight": `${markdown.body.fontWeight}`,
    "--markdown-body-letter-spacing": `${markdown.body.letterSpacing}px`,
    "--markdown-paragraph-spacing": `${markdown.body.paragraphSpacing}px`,
    ...headingToCssVariables("h1", markdown.heading.h1),
    ...headingToCssVariables("h2", markdown.heading.h2),
    ...headingToCssVariables("h3", markdown.heading.h3),
    ...headingToCssVariables("h4", markdown.heading.h4),
    ...headingToCssVariables("h5", markdown.heading.h5),
    ...headingToCssVariables("h6", markdown.heading.h6),
    "--markdown-link-color": markdown.link.color,
    "--markdown-link-hover-color": markdown.link.hoverColor,
    "--markdown-link-underline-thickness": `${markdown.link.underlineThickness}px`,
    "--markdown-link-underline-offset": `${markdown.link.underlineOffset}px`,
    "--markdown-emphasis-color": markdown.emphasis.color,
    "--markdown-strong-weight": `${markdown.emphasis.strongWeight}`,
    "--markdown-list-marker-color": markdown.list.markerColor,
    "--markdown-list-indent": `${markdown.list.indent}px`,
    "--markdown-list-item-spacing": `${markdown.list.itemSpacing}px`,
    "--markdown-list-block-spacing": `${markdown.list.blockSpacing}px`,
    "--markdown-quote-text": markdown.quote.textColor,
    "--markdown-quote-border": markdown.quote.borderColor,
    "--markdown-quote-background": markdown.quote.background,
    "--markdown-quote-padding-x": `${markdown.quote.paddingX}px`,
    "--markdown-quote-padding-y": `${markdown.quote.paddingY}px`,
    "--markdown-quote-margin-y": `${markdown.quote.marginY}px`,
    "--markdown-quote-border-width": `${markdown.quote.borderWidth}px`,
    "--markdown-quote-radius": `${markdown.quote.radius}px`,
    "--markdown-inline-code-text": markdown.inlineCode.textColor,
    "--markdown-inline-code-background": markdown.inlineCode.background,
    "--markdown-inline-code-font-size": `${markdown.inlineCode.fontSize}px`,
    "--markdown-inline-code-line-height": `${markdown.inlineCode.lineHeight}px`,
    "--markdown-inline-code-padding-x": `${markdown.inlineCode.paddingX}px`,
    "--markdown-inline-code-padding-y": `${markdown.inlineCode.paddingY}px`,
    "--markdown-inline-code-radius": `${markdown.inlineCode.radius}px`,
    "--markdown-code-block-text": markdown.codeBlock.textColor,
    "--markdown-code-block-background": markdown.codeBlock.background,
    "--markdown-code-block-font-size": `${markdown.codeBlock.fontSize}px`,
    "--markdown-code-block-line-height": `${markdown.codeBlock.lineHeight}px`,
    "--markdown-code-block-padding-x": `${markdown.codeBlock.paddingX}px`,
    "--markdown-code-block-padding-y": `${markdown.codeBlock.paddingY}px`,
    "--markdown-code-block-margin-y": `${markdown.codeBlock.marginY}px`,
    "--markdown-code-block-radius": `${markdown.codeBlock.radius}px`,
    "--markdown-table-text": markdown.table.textColor,
    "--markdown-table-border": markdown.table.borderColor,
    "--markdown-table-header-background": markdown.table.headerBackground,
    "--markdown-table-alternate-background": markdown.table.alternateBackground,
    "--markdown-table-cell-padding-x": `${markdown.table.cellPaddingX}px`,
    "--markdown-table-cell-padding-y": `${markdown.table.cellPaddingY}px`,
    "--markdown-table-border-width": `${markdown.table.borderWidth}px`,
    "--markdown-table-radius": `${markdown.table.radius}px`,
    "--markdown-table-margin-y": `${markdown.table.marginY}px`,
    "--markdown-divider-color": markdown.divider.color,
    "--markdown-divider-thickness": `${markdown.divider.thickness}px`,
    "--markdown-divider-margin-y": `${markdown.divider.marginY}px`,
    "--markdown-image-border": markdown.image.borderColor,
    "--markdown-image-border-width": `${markdown.image.borderWidth}px`,
    "--markdown-image-radius": `${markdown.image.radius}px`,
    "--markdown-image-margin-y": `${markdown.image.marginY}px`
  };
}

function headingToCssVariables(level: string, heading: MarkdownHeadingTokens): Record<string, string> {
  return {
    [`--markdown-${level}-color`]: heading.color,
    [`--markdown-${level}-font-size`]: `${heading.fontSize}px`,
    [`--markdown-${level}-line-height`]: `${heading.lineHeight}px`,
    [`--markdown-${level}-font-weight`]: `${heading.fontWeight}`,
    [`--markdown-${level}-letter-spacing`]: `${heading.letterSpacing}px`,
    [`--markdown-${level}-margin-top`]: `${heading.marginTop}px`,
    [`--markdown-${level}-margin-bottom`]: `${heading.marginBottom}px`
  };
}
