import type Konva from "konva";
import type { KonvaEventObject } from "konva/lib/Node";
import type { PointerEvent as ReactPointerEvent, RefObject } from "react";

import type { InlineEdit, InlineEditStyle } from "@/features/mermaid-editor/components/konva-canvas/inline-edit-overlays";
import type { TableCellToolbarOperation } from "@/features/mermaid-editor/components/konva-canvas/table-cell-toolbar";
import type { CanvasEdgeMotionVisual, CanvasNodeMotionVisual } from "@/features/mermaid-editor/components/konva-canvas/types";
import type { useKonvaNodeEditorLayout } from "@/features/mermaid-editor/components/konva-canvas/use-konva-inline-edit-session";
import type { useKonvaRenderModel } from "@/features/mermaid-editor/components/konva-canvas/use-konva-render-model";
import type { AlignmentGuide, AlignmentRect } from "@/features/mermaid-editor/lib/alignment-guides";
import type { CanvasGridSpec } from "@/features/mermaid-editor/lib/canvas-grid";
import type { CanvasPoint, HitTarget, InteractionState } from "@/features/mermaid-editor/lib/canvas-interaction";
import type { CanvasProximityScales } from "@/features/mermaid-editor/lib/canvas-motion";
import type { CanvasVisualTokens } from "@/features/mermaid-editor/lib/canvas-visual-state";
import type { EdgeLabelGeometryTokens } from "@/features/mermaid-editor/lib/edge-label-geometry";
import type { EditorTypographyTokens, SpecialNodeThemeTokens } from "@/features/mermaid-editor/lib/editor-theme";
import type { CanvasNode, EditorMode, MermaidGraph, Selection, ViewportState } from "@/features/mermaid-editor/lib/editor-types";
import type { MarkdownDocumentPreview } from "@/features/mermaid-editor/lib/markdown-document";
import type { NodeGeometryTokens } from "@/features/mermaid-editor/lib/node-geometry";
import type { NodeArrangementOperation } from "@/features/mermaid-editor/lib/node-arrangement";
import type { TableCellNavigation, TableCellSelection, TableHeaderSelection } from "@/features/mermaid-editor/lib/table-node";
import type { ViewFilters } from "@/features/mermaid-editor/lib/view-filters";

type RenderModel = ReturnType<typeof useKonvaRenderModel>;

export type KonvaCanvasStageProps = {
  containerRef: RefObject<HTMLDivElement | null>;
  stageRef: RefObject<Konva.Stage | null>;
  dimensions: { width: number; height: number };
  viewport: ViewportState;
  cursorClassName: string;
  graph: MermaidGraph;
  selection: Selection;
  mode: EditorMode;
  panningRequested: boolean;
  dragEnabled: boolean;
  viewFilters: ViewFilters;
  inlineEdit: InlineEdit | null;
  interactionState: InteractionState;
  visualTokens: CanvasVisualTokens;
  gridSpec: CanvasGridSpec;
  nodeThemeTokens: NodeGeometryTokens;
  specialNodeTokens: SpecialNodeThemeTokens;
  edgeLabelThemeTokens: EdgeLabelGeometryTokens;
  typography: EditorTypographyTokens;
  runtimeCreateScale: number;
  imageDisplaySrcBySrc: Record<string, string>;
  markdownDocumentPreviewByNodeId: Record<string, MarkdownDocumentPreview>;
  alignmentGuides: AlignmentGuide[];
  hoveredNodeId: string | null;
  hoveredSubgraphId: string | null;
  hoveredEdgeId: string | null;
  hoveredHitTarget: HitTarget;
  selectedSubgraphIds: RenderModel["selectedSubgraphIds"];
  selectedNodeRects: AlignmentRect[];
  scopedSubgraphGeometries: RenderModel["scopedSubgraphGeometries"];
  scopedVisibleEdges: RenderModel["scopedVisibleEdges"];
  scopedRenderedNodes: RenderModel["scopedRenderedNodes"];
  exitingNodes: CanvasNode[];
  nodeGeometryById: RenderModel["nodeGeometryById"];
  geometrySpec: RenderModel["geometrySpec"];
  edgeLabelSpec: RenderModel["edgeLabelSpec"];
  edgeMotion: Record<string, CanvasEdgeMotionVisual>;
  nodeMotion: Record<string, CanvasNodeMotionVisual>;
  nodeProximityScale: CanvasProximityScales;
  resolvedEdgeGeometry: RenderModel["resolvedEdgeGeometry"];
  selectedSingleEdge: RenderModel["selectedSingleEdge"];
  selectedSingleEdgeGeometry: RenderModel["selectedSingleEdgeGeometry"];
  selectionBox: RenderModel["selectionBox"];
  retargetDraft: RenderModel["retargetDraft"];
  connectionPreview: RenderModel["connectionPreview"];
  connectionDraftGeometry: RenderModel["connectionDraftGeometry"];
  connectionDraftVisual: RenderModel["connectionDraftVisual"];
  retargetPreview: RenderModel["retargetPreview"];
  retargetDraftGeometry: RenderModel["retargetDraftGeometry"];
  connectionTargetNodeId: string | null;
  connectionInvalidNodeId: string | null;
  connectionTargetSubgraphId: string | null;
  connectionInvalidSubgraphId: string | null;
  nodeContextMenu: { nodeId: string; x: number; y: number } | null;
  editStyle: InlineEditStyle | null;
  activeScale: number;
  nodeEditorLayout: ReturnType<typeof useKonvaNodeEditorLayout>;
  nodeEditorRef: RefObject<HTMLTextAreaElement | null>;
  nodeEditorMeasureRef: RefObject<HTMLDivElement | null>;
  selectedTableCell: TableCellSelection | null;
  onWheel: (event: KonvaEventObject<WheelEvent>) => void;
  onCanvasPointerDown: (event: KonvaEventObject<MouseEvent>, explicitHit?: HitTarget, worldOverride?: CanvasPoint) => void;
  onCanvasPointerMove: (event: KonvaEventObject<MouseEvent>) => void;
  onCanvasPointerUp: (event: KonvaEventObject<MouseEvent>) => void;
  onCanvasPointerLeave: () => void;
  onCanvasPointerTracking: (event: ReactPointerEvent<HTMLDivElement>) => void;
  onCanvasClick: (event: KonvaEventObject<MouseEvent>, hit: HitTarget) => void;
  onCanvasTap: (event: KonvaEventObject<Event>, hit: HitTarget) => void;
  onCanvasDoubleClick: (event: KonvaEventObject<MouseEvent>, hit: HitTarget) => void;
  onStartNodeDrag: (nodeId: string) => void;
  onStartSubgraphDrag: (subgraphId: string) => void;
  onMoveNode: (node: CanvasNode, target: Konva.Node) => void;
  onMoveSubgraph: (subgraphId: string, target: Konva.Node) => void;
  onEndDrag: () => void;
  onArrangeNodes: (operation: NodeArrangementOperation) => void;
  onNodeContextMenu: (event: KonvaEventObject<PointerEvent | MouseEvent>, node: CanvasNode) => void;
  onCloseNodeContextMenu: () => void;
  onOpenNodeAction?: (node: CanvasNode) => void;
  onOpenNodeImage?: (node: CanvasNode) => void;
  onEditNodeAction?: (node: CanvasNode) => void;
  onRequestMarkdownDocumentPreview?: (node: CanvasNode) => void;
  onSelectTableCell: (selection: TableCellSelection | null) => void;
  onStartTableCellEdit: (selection: TableCellSelection) => void;
  onStartTableHeaderEdit: (selection: TableHeaderSelection) => void;
  onResizeTableColumn: (nodeId: string, columnId: string, width: number) => void;
  onTableCellOperation: (operation: TableCellToolbarOperation) => void;
  onInlineEditChange: (next: InlineEdit) => void;
  onInlineEditCommit: (save: boolean, navigation?: TableCellNavigation) => void;
  onTablePaste: (text: string) => void;
};

export type KonvaCanvasModelStageProps = Omit<KonvaCanvasStageProps,
  | "nodeContextMenu" | "onCanvasPointerDown" | "onCanvasPointerMove" | "onCanvasPointerUp"
  | "onCanvasPointerLeave" | "onCanvasPointerTracking" | "onCanvasClick" | "onCanvasTap"
  | "onCanvasDoubleClick" | "onStartNodeDrag" | "onStartSubgraphDrag" | "onNodeContextMenu" | "onCloseNodeContextMenu">;
